export default {
    // 用于sessionStore存放初始Vuex状态
    initStateJson:"vuex_init_state_json_info",
    // 用于登录信息加密
    publicKey:"MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhZRMfkhJqOSJ2J9Im9wis/l/OGlViSyujS9hy8fQ0CTr+v87xDpoQu8LWN91CIRZnCADI0UqOscYtmykDDzyLzK9XktmDnZRII8uPYJirmgSPr0LIO3sai+fUpV3d4rJ9NBXFl/juQX1uHeRsDaGKdQwut/crOUfyaXWlKdrF8UQyrO08gjTbJWTBI7dpp85NciJm0/uQOLg234m2mhNuyWZB/Ov+eqTxMQeqa+zXRYmJtfKHjI+FNoM2hJ9sgos2/nHfd9wfn5QoVDHxNZVtuCIvcCGlfluIWP0qkoJp56QCnOmJAI50FGnvk6lv8YKpLWvYYtVNB0kYsDFEQnHbwIDAQAB",
}
